# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default
  demands:
   - agent.name -equals KADN  

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: 'project.json'
    outputType: 'Process'
    orchestratorConnection: 'DevopsSC'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'DevopsSC'
    packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
    folderName: 'Shared'